training_pipeline_config:
  pipeline_name: banking
  artifact_dir: artifact


data_ingestion_config:
  dataset_download_url: "uciml/default-of-credit-card-clients-dataset"
  dataset_file_name : "UCI_Credit_Card.csv"
  dataset_file_zip : "UCI_Credit_Card.csv.zip"
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test


data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  add_bedroom_per_room: true
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  